- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
    sg_id: sg-0a1041abc3d14180f
    ami_id: ami-02b64aa047cb5edf5
    env1: dev
    region: us-east-1
    instances:
    - mongodb
    - catalogue

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env1 }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env1 }}"
        Name: "{{ item }}-{{ env1 }}"
    environment:
      AWS_DEFAULT_REGION: "{{ region }}" 
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
